schema: '**/*.graphqls'
schemaEntrypoint: 'lib/graphql/type-defs.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: node_modules/.cache